#!/usr/bin/env python3
from os import chdir, popen, system

print('--------------------------------------- Hook ---------------------------------------')
updated_files = popen("git diff -r --name-only ORIG_HEAD HEAD").read()

chdir('Source/')
if '.env.example' in updated_files:
    env_dict = {}
    with open('.env.example') as env:
        for envLine in env.readlines():
            splitData = envLine.split("=")
            if splitData[0] == '\n':
                continue

            if splitData[1] == '\n':
                splitData[1] = ''

            splitData[1] = splitData[1].rstrip('\n')
            env_dict[splitData[0]] = splitData[1]

    env.closed

    if env_dict['DB_MIGRATION_REFRESH']:
        print('Performing Migration Refresh...')
        system('php artisan migrate:refresh')
    elif env_dict['DB_MIGRATION']:
        print('Performing Migration...')
        system('php artisan migrate')
    else:
        pass
else:
    print('NO ENV Changes')